//////////////////////////////////////////////////////////
// This class has been automatically generated on
// Wed Jun  2 16:10:16 2010 by ROOT version 5.22/00d
// from TTree EwkDqmTree/EwkDqmTree
// found on file: /scratch/jleonard/DQM/ewkElecStandaloneDQM-2010GoodCollsv9-1jun10.root
//////////////////////////////////////////////////////////

#ifndef EwkDqmTree_h
#define EwkDqmTree_h

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <TH1F.h>
#include <TGraphAsymmErrors.h>
#include <iostream>
#include <algorithm>
#include <string>

const Int_t kMax1 = 62;
const Int_t kMax2 = 12;

//
//   Working point variables, in order on twiki
//   0: NO CUTS 1: 95%, 2: 90%, 3: 85%, 4: 80%, 5: 70%, 6: 60%
// 

const Int_t kWP = 7;
//   const Int_t kEta = 2; // 0 barrel, 1 endcap

// in general the cuts go "keep if quantity less than this number", except where marked

// conversion rejection
const UInt_t nHitsMiss[kWP]  = {999, 1, 1, 1, 0, 0, 0}; 
const Float_t dist[kWP]      = {0., 0., 0.02, 0.02, 0.02, 0.02, 0.02}; // REJECT if less than this number
const Float_t dcotTheta[kWP] = {0., 0., 0.02, 0.02, 0.02, 0.02, 0.02}; // REJECT if less than this number

// isolation -- which to use?? combined?
//   const Float_t isolVar[kEta][kWP];
const Float_t isolVarBarrel[kWP] = {999., 0.15, 0.10, 0.09, 0.07, 0.04, 0.03};
const Float_t isolVarEndcap[kWP] = {999., 0.1, 0.07, 0.06, 0.06, 0.03, 0.02};

// ID
/*    const Float_t sieie[kEta][kWP]; */
/*    const Float_t detain[kEta][kWP]; */
/*    const Float_t dphiin[kEta][kWP]; */
/*    const Float_t hoe[kEta][kWP]; */
const Float_t sieieBarrel[kWP]  = {999., 0.01, 0.01, 0.01, 0.01, 0.01, 0.01};
const Float_t detainBarrel[kWP] = {999., 0.007, 0.007, 0.006, 0.004, 0.004, 0.004 };
const Float_t dphiinBarrel[kWP] = {999., 0.8, 0.8, 0.06, 0.06, 0.03, 0.025};
const Float_t hoeBarrel[kWP]    = {999., 0.5, 0.12, 0.04, 0.04, 0.025, 0.025};
const Float_t sieieEndcap[kWP]  = {999., 0.03, 0.03, 0.03, 0.03, 0.03, 0.03 };
const Float_t detainEndcap[kWP] = {999., 0.01, 0.009, 0.007, 0.007, 0.005, 0.005 };
const Float_t dphiinEndcap[kWP] = {999., 0.7, 0.7, 0.04, 0.03, 0.02, 0.02};
const Float_t hoeEndcap[kWP]    = {999., 0.07, 0.05, 0.025, 0.025, 0.025, 0.025};


class EwkDqmTree {
public :
   TTree          *fChain;   //!pointer to the analyzed TTree or TChain
   Int_t           fCurrent; //!current Tree number in a TChain

   const char     *inputFilename;
   //   const char      outputFilename[128];
   char            outputFilename[128];
   TFile          *outputHistoFile;


   const Int_t     wpIndex;
   Bool_t          result_WP;

   Bool_t          result_match_L1obj_;
   //   Bool_t          result_match_HLTobj_; // don't need to worry about this, all HLT objects automatically pass given threshold

   Bool_t          result_HLTElec10_; // HLT_Ele10_LW_L1R
   Bool_t          result_HLTElec15_; // HLT_Ele15_LW_L1R
   Bool_t          result_HLTPhot10_; // HLT_Photon10_L1R
   Bool_t          result_HLTPhot15_; // HLT_Photon15_L1R
   Bool_t          result_L1EG5_; // L1_SingleEG5
   Bool_t          result_L1EG8_; // L1_SingleEG8

   Bool_t          result_matched_HLTElec10_;
   Bool_t          result_matched_HLTElec15_;
   Bool_t          result_matched_HLTPhot10_;
   Bool_t          result_matched_HLTPhot15_;
   Bool_t          result_matched_L1EG5_;
   Bool_t          result_matched_L1EG8_;


   // Eff nums/denoms/plots

   //   enum {WP_NONE, WP_95, WP_90, WP_85, WP_80, WP_70, WP_60}

/*    enum {ETA_BARREL, ETA_ENDCAP, ETA_BOTH, ETA_LAST}; */
/*    enum {SEED_ECAL, SEED_TRACKER, SEED_BOTH, SEED_LAST}; */
/*    enum {TRIG_MATCHED, TRIG_UNMATCHED, TRIG_MATCH_LAST}; */
/*    enum {VS_ELEC_SC_ET, VS_ETA, VS_LAST}; */
/*    enum {HLT_ELEC10, HLT_ELEC15, HLT_PHOT10, HLT_PHOT15, L1_EG5, L1_EG8, TRIG_OF_INTEREST_LAST}; */

   //   TH1F * eff[ETA_LAST][SEED_LAST][TRIG_MATCH_LAST][VS_LAST][TRIG_OF_INTEREST_LAST];

   Float_t highestScEtElectronScEt;
   Float_t highestScEtElectronEta;
   Float_t highestScEtElectronPhi;
   Int_t highestScEtElectronIndex;

   Float_t highestScEtElectronPt;

   Bool_t highestScEtElectronIsBarrel;
   Bool_t highestScEtElectronIsEndcap;

   Bool_t highestScEtElectronIsEcalDriven;
   Bool_t highestScEtElectronIsTrackerDriven;

   Int_t highestScEtElectronNHitsMiss;
   Float_t highestScEtElectronDist;
   Float_t highestScEtElectronDcotTheta;

   Float_t highestScEtElectronIsoVar;
   Float_t highestScEtElectronEcalIso;
   Float_t highestScEtElectronHcalIso;
   Float_t highestScEtElectronTrackIso;

   Float_t highestScEtElectronSieie;
   Float_t highestScEtElectronDetain;
   Float_t highestScEtElectronDphiin;
   Float_t highestScEtElectronHoE;



   // BARREL
   TH1F * eff_denom_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BARREL__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   // ENDCAP
   TH1F * eff_denom_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_ENDCAP__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   // BARREL+ENDCAP
   TH1F * eff_denom_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_ECAL__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_TRACKER__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_MATCHED__VS_ETA__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ELEC_SC_ET__L1_EG8_WP_; */

   TH1F * eff_denom_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_;
   TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_;
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_; */
/*    TH1F * eff_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_ELEC15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT10_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__HLT_PHOT15_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG5_WP_; */
/*    TH1F * eff_num_ETA_BOTH__SEED_BOTH__TRIG_UNMATCHED__VS_ETA__L1_EG8_WP_; */



   // Declaration of leaf types
   UInt_t          runNumber;
   UInt_t          lumiSection;
   UInt_t          eventNumber;
   Bool_t          ele_trig;
   Int_t           triggersOfInterest_;
   string          triggersOfInterest_first[kMax1];
   Bool_t          triggersOfInterest_second[kMax1];   //[_]
   Int_t           l1TriggersOfInterest_;
   string          l1TriggersOfInterest_first[kMax2];
   Bool_t          l1TriggersOfInterest_second[kMax2];   //[_]
   Bool_t          hasWCand;
   Bool_t          hasZCand;
   Int_t           ele_nelectrons; // originally 6
   Bool_t          ele_isEcalDriven[10];   //[ele_nelectrons]
   Bool_t          ele_isTrackerDriven[10];   //[ele_nelectrons]
   Bool_t          ele_isBarrel[10];   //[ele_nelectrons]
   Bool_t          ele_isEndcap[10];   //[ele_nelectrons]
   Float_t         ele_eta[10];   //[ele_nelectrons]
   Float_t         ele_phi[10];   //[ele_nelectrons]
   Float_t         ele_dxy[10];   //[ele_nelectrons]
   Float_t         ele_pt[10];   //[ele_nelectrons]
   Float_t         ele_energy[10];   //[ele_nelectrons]
   Float_t         ele_ecalenergy[10];   //[ele_nelectrons]
   Float_t         ele_ecalenergyerror[10];   //[ele_nelectrons]
   Float_t         ele_et[10];   //[ele_nelectrons]
   Float_t         ele_p[10];   //[ele_nelectrons]
   Float_t         ele_electronmomentumerror[10];   //[ele_nelectrons]
   Float_t         ele_px[10];   //[ele_nelectrons]
   Float_t         ele_py[10];   //[ele_nelectrons]
   Float_t         ele_pz[10];   //[ele_nelectrons]
   Float_t         ele_deltaetaeleclustertrackatcalo[10];   //[ele_nelectrons]
   Float_t         ele_deltaetaseedclustertrackatcalo[10];   //[ele_nelectrons]
   Float_t         ele_deltaetasuperclustertrackatvtx[10];   //[ele_nelectrons]
   Float_t         ele_deltaphieleclustertrackatcalo[10];   //[ele_nelectrons]
   Float_t         ele_deltaphiseedclustertrackatcalo[10];   //[ele_nelectrons]
   Float_t         ele_deltaphisuperclustertrackatvtx[10];   //[ele_nelectrons]
   Float_t         ele_trackpositionatvtxx[10];   //[ele_nelectrons]
   Float_t         ele_trackpositionatvtxy[10];   //[ele_nelectrons]
   Float_t         ele_trackpositionatvtxz[10];   //[ele_nelectrons]
   Float_t         ele_trackmomentumatvtxx[10];   //[ele_nelectrons]
   Float_t         ele_trackmomentumatvtxy[10];   //[ele_nelectrons]
   Float_t         ele_trackmomentumatvtxz[10];   //[ele_nelectrons]
   Float_t         ele_trackpositionatcalox[10];   //[ele_nelectrons]
   Float_t         ele_trackpositionatcaloy[10];   //[ele_nelectrons]
   Float_t         ele_trackpositionatcaloz[10];   //[ele_nelectrons]
   Float_t         ele_trackmomentumatcalox[10];   //[ele_nelectrons]
   Float_t         ele_trackmomentumatcaloy[10];   //[ele_nelectrons]
   Float_t         ele_trackmomentumatcaloz[10];   //[ele_nelectrons]
   Float_t         ele_eeleclusteroverpout[10];   //[ele_nelectrons]
   Float_t         ele_eseedclusteroverp[10];   //[ele_nelectrons]
   Float_t         ele_eseedclusteroverpout[10];   //[ele_nelectrons]
   Float_t         ele_esuperclusteroverp[10];   //[ele_nelectrons]
   Float_t         ele_dr03ecalrechitsumet[10];   //[ele_nelectrons]
   Float_t         ele_dr03hcaldepth1towersumet[10];   //[ele_nelectrons]
   Float_t         ele_dr03hcaldepth2towersumet[10];   //[ele_nelectrons]
   Float_t         ele_dr03hcaltowersumet[10];   //[ele_nelectrons]
   Float_t         ele_dr03tksumpt[10];   //[ele_nelectrons]
   Float_t         ele_dr04ecalrechitsumet[10];   //[ele_nelectrons]
   Float_t         ele_dr04hcaldepth1towersumet[10];   //[ele_nelectrons]
   Float_t         ele_dr04hcaldepth2towersumet[10];   //[ele_nelectrons]
   Float_t         ele_dr04hcaltowersumet[10];   //[ele_nelectrons]
   Float_t         ele_dr04tksumpt[10];   //[ele_nelectrons]
   Float_t         ele_e1x5[10];   //[ele_nelectrons]
   Float_t         ele_e2x5max[10];   //[ele_nelectrons]
   Float_t         ele_e5x5[10];   //[ele_nelectrons]
   Float_t         ele_r1x5[10];   //[ele_nelectrons]
   Float_t         ele_r2x5max[10];   //[ele_nelectrons]
   Float_t         ele_scpreshowerenergy[10];   //[ele_nelectrons]
   Float_t         ele_scetawidth[10];   //[ele_nelectrons]
   Float_t         ele_scphiwidth[10];   //[ele_nelectrons]
   Float_t         ele_scr9[10];   //[ele_nelectrons]
   Float_t         ele_sceseedoveresupercluster[10];   //[ele_nelectrons]
   Float_t         ele_rmax3x3[10];   //[ele_nelectrons]
   Float_t         ele_hcaldepth1overecal[10];   //[ele_nelectrons]
   Float_t         ele_hcaldepth2overecal[10];   //[ele_nelectrons]
   Float_t         ele_hcaloverecal[10];   //[ele_nelectrons]
   Float_t         ele_sigmaetaeta[10];   //[ele_nelectrons]
   Float_t         ele_sigmaietaieta[10];   //[ele_nelectrons]
   Float_t         ele_basicclusterssize[10];   //[ele_nelectrons]
   Float_t         ele_numberofbrems[10];   //[ele_nelectrons]
   Float_t         ele_fbrem[10];   //[ele_nelectrons]
   Float_t         ele_scpixcharge[10];   //[ele_nelectrons]
   Float_t         ele_gsfcharge[10];   //[ele_nelectrons]
   Float_t         ele_ctfcharge[10];   //[ele_nelectrons]
   Float_t         ele_isgsfscpixchargeconsistent[10];   //[ele_nelectrons]
   Float_t         ele_isgsfctfchargeconsistent[10];   //[ele_nelectrons]
   Float_t         ele_isgsfctfscpixchargeconsistent[10];   //[ele_nelectrons]
   Float_t         ele_charge[10];   //[ele_nelectrons]
   Float_t         ele_vertexChi2[10];   //[ele_nelectrons]
   Float_t         ele_vertexNdof[10];   //[ele_nelectrons]
   Float_t         ele_vertexNormalizedChi2[10];   //[ele_nelectrons]
   Float_t         ele_vx[10];   //[ele_nelectrons]
   Float_t         ele_vy[10];   //[ele_nelectrons]
   Float_t         ele_vz[10];   //[ele_nelectrons]
   Int_t           ele_nexpectedinnerhits[10];
   Float_t         ele_dist[10];
   Float_t         ele_dcottheta[10];
   UInt_t          sc_nSuperClusters; // originally 27
   UInt_t          sc_nSuperClustersBarrel;
   UInt_t          sc_nSuperClustersEndcap;
   Bool_t          sc_isBarrel[40];   //[sc_nSuperClusters]
   Bool_t          sc_isEndcap[40];   //[sc_nSuperClusters]
   Float_t         sc_energy[40];   //[sc_nSuperClusters]
   Float_t         sc_eta[40];   //[sc_nSuperClusters]
   Float_t         sc_phi[40];   //[sc_nSuperClusters]
   Float_t         sc_et[40];   //[sc_nSuperClusters]
   Float_t         sc_rawEnergy[40];   //[sc_nSuperClusters]
   Float_t         sc_preshowerEnergy[40];   //[sc_nSuperClusters]
   Float_t         sc_etaWidth[40];   //[sc_nSuperClusters]
   Float_t         sc_phiWidth[40];   //[sc_nSuperClusters]
   Int_t           sc_nBasicClusters[40];   //[sc_nSuperClusters]
   Float_t         sc_r9[40];   //[sc_nSuperClusters]
   Float_t         sc_eSeedOverESuperCluster[40];   //[sc_nSuperClusters]
   UInt_t          l1_nL1Obj;
   Float_t         l1_et[8];   //[l1_nL1Obj]
   Float_t         l1_eta[8];   //[l1_nL1Obj]
   Float_t         l1_phi[8];   //[l1_nL1Obj]
   UInt_t          hlt_nHltObj_Elec10;
   UInt_t          hlt_nHltObj_Elec15;
   UInt_t          hlt_nHltObj_Phot10;
   UInt_t          hlt_nHltObj_Phot15;
   Float_t         hlt_Elec10_et[8];   //[hlt_nHltObj_Elec10]
   Float_t         hlt_Elec10_eta[8];   //[hlt_nHltObj_Elec10]
   Float_t         hlt_Elec10_phi[8];   //[hlt_nHltObj_Elec10]
   Float_t         hlt_Elec15_et[7];   //[hlt_nHltObj_Elec15]
   Float_t         hlt_Elec15_eta[7];   //[hlt_nHltObj_Elec15]
   Float_t         hlt_Elec15_phi[7];   //[hlt_nHltObj_Elec15]
   Float_t         hlt_Phot10_et[8];   //[hlt_nHltObj_Phot10]
   Float_t         hlt_Phot10_eta[8];   //[hlt_nHltObj_Phot10]
   Float_t         hlt_Phot10_phi[8];   //[hlt_nHltObj_Phot10]
   Float_t         hlt_Phot15_et[7];   //[hlt_nHltObj_Phot15]
   Float_t         hlt_Phot15_eta[7];   //[hlt_nHltObj_Phot15]
   Float_t         hlt_Phot15_phi[7];   //[hlt_nHltObj_Phot15]


   // List of branches
   TBranch        *b_runNumber;   //!
   TBranch        *b_lumiSection;   //!
   TBranch        *b_eventNumber;   //!
   TBranch        *b_ele_trig;   //!
   TBranch        *b_triggersOfInterest;   //!    CHANGE FROM *b__
   TBranch        *b_triggersOfInterest_first;   //!
   TBranch        *b_triggersOfInterest_second;   //!
   TBranch        *b_l1TriggersOfInterest;   //!   CHANGED FROM *b__
   TBranch        *b_l1TriggersOfInterest_first;   //!
   TBranch        *b_l1TriggersOfInterest_second;   //!
   TBranch        *b_hasWCand;   //!
   TBranch        *b_hasZCand;   //!
   TBranch        *b_ele_nelectrons;   //!
   TBranch        *b_ele_isEcalDriven;   //!
   TBranch        *b_ele_isTrackerDriven;   //!
   TBranch        *b_ele_isBarrel;   //!
   TBranch        *b_ele_isEndcap;   //!
   TBranch        *b_ele_eta;   //!
   TBranch        *b_ele_phi;   //!
   TBranch        *b_ele_dxy;   //!
   TBranch        *b_ele_pt;   //!
   TBranch        *b_ele_energy;   //!
   TBranch        *b_ele_ecalenergy;   //!
   TBranch        *b_ele_ecalenergyerror;   //!
   TBranch        *b_ele_et;   //!
   TBranch        *b_ele_p;   //!
   TBranch        *b_ele_electronmomentumerror;   //!
   TBranch        *b_ele_px;   //!
   TBranch        *b_ele_py;   //!
   TBranch        *b_ele_pz;   //!
   TBranch        *b_ele_deltaetaeleclustertrackatcalo;   //!
   TBranch        *b_ele_deltaetaseedclustertrackatcalo;   //!
   TBranch        *b_ele_deltaetasuperclustertrackatvtx;   //!
   TBranch        *b_ele_deltaphieleclustertrackatcalo;   //!
   TBranch        *b_ele_deltaphiseedclustertrackatcalo;   //!
   TBranch        *b_ele_deltaphisuperclustertrackatvtx;   //!
   TBranch        *b_ele_trackpositionatvtxx;   //!
   TBranch        *b_ele_trackpositionatvtxy;   //!
   TBranch        *b_ele_trackpositionatvtxz;   //!
   TBranch        *b_ele_trackmomentumatvtxx;   //!
   TBranch        *b_ele_trackmomentumatvtxy;   //!
   TBranch        *b_ele_trackmomentumatvtxz;   //!
   TBranch        *b_ele_trackpositionatcalox;   //!
   TBranch        *b_ele_trackpositionatcaloy;   //!
   TBranch        *b_ele_trackpositionatcaloz;   //!
   TBranch        *b_ele_trackmomentumatcalox;   //!
   TBranch        *b_ele_trackmomentumatcaloy;   //!
   TBranch        *b_ele_trackmomentumatcaloz;   //!
   TBranch        *b_ele_eeleclusteroverpout;   //!
   TBranch        *b_ele_eseedclusteroverp;   //!
   TBranch        *b_ele_eseedclusteroverpout;   //!
   TBranch        *b_ele_esuperclusteroverp;   //!
   TBranch        *b_ele_dr03ecalrechitsumet;   //!
   TBranch        *b_ele_dr03hcaldepth1towersumet;   //!
   TBranch        *b_ele_dr03hcaldepth2towersumet;   //!
   TBranch        *b_ele_dr03hcaltowersumet;   //!
   TBranch        *b_ele_dr03tksumpt;   //!
   TBranch        *b_ele_dr04ecalrechitsumet;   //!
   TBranch        *b_ele_dr04hcaldepth1towersumet;   //!
   TBranch        *b_ele_dr04hcaldepth2towersumet;   //!
   TBranch        *b_ele_dr04hcaltowersumet;   //!
   TBranch        *b_ele_dr04tksumpt;   //!
   TBranch        *b_ele_e1x5;   //!
   TBranch        *b_ele_e2x5max;   //!
   TBranch        *b_ele_e5x5;   //!
   TBranch        *b_ele_r1x5;   //!
   TBranch        *b_ele_r2x5max;   //!
   TBranch        *b_ele_scpreshowerenergy;   //!
   TBranch        *b_ele_scetawidth;   //!
   TBranch        *b_ele_scphiwidth;   //!
   TBranch        *b_ele_scr9;   //!
   TBranch        *b_ele_sceseedoveresupercluster;   //!
   TBranch        *b_ele_rmax3x3;   //!
   TBranch        *b_ele_hcaldepth1overecal;   //!
   TBranch        *b_ele_hcaldepth2overecal;   //!
   TBranch        *b_ele_hcaloverecal;   //!
   TBranch        *b_ele_sigmaetaeta;   //!
   TBranch        *b_ele_sigmaietaieta;   //!
   TBranch        *b_ele_basicclusterssize;   //!
   TBranch        *b_ele_numberofbrems;   //!
   TBranch        *b_ele_fbrem;   //!
   TBranch        *b_ele_scpixcharge;   //!
   TBranch        *b_ele_gsfcharge;   //!
   TBranch        *b_ele_ctfcharge;   //!
   TBranch        *b_ele_isgsfscpixchargeconsistent;   //!
   TBranch        *b_ele_isgsfctfchargeconsistent;   //!
   TBranch        *b_ele_isgsfctfscpixchargeconsistent;   //!
   TBranch        *b_ele_charge;   //!
   TBranch        *b_ele_vertexChi2;   //!
   TBranch        *b_ele_vertexNdof;   //!
   TBranch        *b_ele_vertexNormalizedChi2;   //!
   TBranch        *b_ele_vx;   //!
   TBranch        *b_ele_vy;   //!
   TBranch        *b_ele_vz;   //!
   TBranch        *b_ele_nexpectedinnerhits;
   TBranch        *b_ele_dist;
   TBranch        *b_ele_dcottheta;
   TBranch        *b_hlt_nHltObj_Elec10;   //!
   TBranch        *b_hlt_nHltObj_Elec15;   //!
   TBranch        *b_hlt_nHltObj_Phot10;   //!
   TBranch        *b_hlt_nHltObj_Phot15;   //!
   TBranch        *b_hlt_Elec10_et;   //!
   TBranch        *b_hlt_Elec10_eta;   //!
   TBranch        *b_hlt_Elec10_phi;   //!
   TBranch        *b_hlt_Elec15_et;   //!
   TBranch        *b_hlt_Elec15_eta;   //!
   TBranch        *b_hlt_Elec15_phi;   //!
   TBranch        *b_hlt_Phot10_et;   //!
   TBranch        *b_hlt_Phot10_eta;   //!
   TBranch        *b_hlt_Phot10_phi;   //!
   TBranch        *b_hlt_Phot15_et;   //!
   TBranch        *b_hlt_Phot15_eta;   //!
   TBranch        *b_hlt_Phot15_phi;   //!
   TBranch        *b_l1_nL1Obj;   //!
   TBranch        *b_l1_et;   //!
   TBranch        *b_l1_eta;   //!
   TBranch        *b_l1_phi;   //!

   TBranch        *b_sc_nSuperClusters;   //!
   TBranch        *b_sc_nSuperClustersBarrel;   //!
   TBranch        *b_sc_nSuperClustersEndcap;   //!
   TBranch        *b_sc_isBarrel;   //!
   TBranch        *b_sc_isEndcap;   //!
   TBranch        *b_sc_energy;   //!
   TBranch        *b_sc_eta;   //!
   TBranch        *b_sc_phi;   //!
   TBranch        *b_sc_et;   //!
   TBranch        *b_sc_rawEnergy;   //!
   TBranch        *b_sc_preshowerEnergy;   //!
   TBranch        *b_sc_etaWidth;   //!
   TBranch        *b_sc_phiWidth;   //!
   TBranch        *b_sc_nBasicClusters;   //!
   TBranch        *b_sc_r9;   //!
   TBranch        *b_sc_eSeedOverESuperCluster;   //!

   //   EwkDqmTree(TTree *tree=0);
   EwkDqmTree(const char* filename, const Int_t index, TTree *tree=0);
   virtual ~EwkDqmTree();
   virtual Int_t    Cut(Long64_t entry);
   virtual Int_t    GetEntry(Long64_t entry);
   virtual Long64_t LoadTree(Long64_t entry);
   virtual void     Init(TTree *tree);
   virtual void     Loop();
   virtual Bool_t   Notify();
   virtual void     Show(Long64_t entry = -1);
   virtual void     InitHistograms();
   virtual void     WriteHistograms();
   virtual void     DeleteHistograms();
   //   virtual void     DrawEfficiency(TString histoName, TString denomName, TString imageName, Double_t lowBins[], const int binArraySize);
   virtual void     DrawEfficiency(TH1F * numHist, TH1F * denomHist, TString imageName, Double_t lowBins[], const int binArraySize);
   virtual void     SavePlot(const char* filename);

};

#endif

#ifdef EwkDqmTree_cxx
//EwkDqmTree::EwkDqmTree(TTree *tree)
EwkDqmTree::EwkDqmTree(const char *filename, const Int_t index, TTree *tree):
  inputFilename(filename),
     //     outputFilename(std::string("effPlots-").append(filename)),
     wpIndex(index)
{
  // if parameter tree is not specified (or zero), connect the file
  // used to generate this class and read the Tree.
  if (tree == 0) 
    {
      //      TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("/scratch/jleonard/DQM/ewkElecStandaloneDQM-2010GoodCollsv9-1jun10.root");
      TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject(inputFilename);
      
      if (!f) 
	{
	  //         f = new TFile("/scratch/jleonard/DQM/ewkElecStandaloneDQM-2010GoodCollsv9-1jun10.root");
	  f = new TFile(inputFilename);
	  //	  f->cd("/scratch/jleonard/DQM/ewkElecStandaloneDQM-2010GoodCollsv9-1jun10.root:/ewkElecStandaloneDQM");
	  f->cd(TString(inputFilename).Append(":/ewkElecStandaloneDQM"));
	}
      tree = (TTree*)gDirectory->Get("EwkDqmTree");
      
    }
  Init(tree);
  InitHistograms();

  //  sprintf(outputFilename,"effs-10jun10-%s",inputFilename);
  sprintf(outputFilename,"effs-10jun10.root");
  std::cout << "inputFilename is " << inputFilename << std::endl;
  std::cout << "outputFilename is " << outputFilename << std::endl;
  outputHistoFile = new TFile(outputFilename,"RECREATE");

}

EwkDqmTree::~EwkDqmTree()
{
   if (!fChain) return;
   delete fChain->GetCurrentFile();

   gROOT->cd();
   outputHistoFile->Close();
   delete outputHistoFile;

   //   DeleteHistograms();
}

Int_t EwkDqmTree::GetEntry(Long64_t entry)
{
// Read contents of entry.
   if (!fChain) return 0;
   return fChain->GetEntry(entry);
}
Long64_t EwkDqmTree::LoadTree(Long64_t entry)
{
// Set the environment to read one entry
   if (!fChain) return -5;
   Long64_t centry = fChain->LoadTree(entry);
   if (centry < 0) return centry;
   if (!fChain->InheritsFrom(TChain::Class()))  return centry;
   TChain *chain = (TChain*)fChain;
   if (chain->GetTreeNumber() != fCurrent) {
      fCurrent = chain->GetTreeNumber();
      Notify();
   }
   return centry;
}

void EwkDqmTree::Init(TTree *tree)
{
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the branch addresses and branch
   // pointers of the tree will be set.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).

   // Set branch addresses and branch pointers
   if (!tree) return;
   fChain = tree;
   fCurrent = -1;
   fChain->SetMakeClass(1);

   fChain->SetBranchAddress("runNumber", &runNumber, &b_runNumber);
   fChain->SetBranchAddress("lumiSection", &lumiSection, &b_lumiSection);
   fChain->SetBranchAddress("eventNumber", &eventNumber, &b_eventNumber);
   fChain->SetBranchAddress("ele_trig", &ele_trig, &b_ele_trig);
   fChain->SetBranchAddress("triggersOfInterest", &triggersOfInterest_, &b_triggersOfInterest); // last arg changed from &b__
   fChain->SetBranchAddress("triggersOfInterest.first", triggersOfInterest_first, &b_triggersOfInterest_first);
   fChain->SetBranchAddress("triggersOfInterest.second", triggersOfInterest_second, &b_triggersOfInterest_second);
   fChain->SetBranchAddress("l1TriggersOfInterest", &l1TriggersOfInterest_, &b_l1TriggersOfInterest); // last arg changed from &b__
   fChain->SetBranchAddress("l1TriggersOfInterest.first", l1TriggersOfInterest_first, &b_l1TriggersOfInterest_first);
   fChain->SetBranchAddress("l1TriggersOfInterest.second", l1TriggersOfInterest_second, &b_l1TriggersOfInterest_second);
   fChain->SetBranchAddress("hasWCand", &hasWCand, &b_hasWCand);
   fChain->SetBranchAddress("hasZCand", &hasZCand, &b_hasZCand);
   fChain->SetBranchAddress("ele_nelectrons", &ele_nelectrons, &b_ele_nelectrons);
   fChain->SetBranchAddress("ele_isEcalDriven", ele_isEcalDriven, &b_ele_isEcalDriven);
   fChain->SetBranchAddress("ele_isTrackerDriven", ele_isTrackerDriven, &b_ele_isTrackerDriven);
   fChain->SetBranchAddress("ele_isBarrel", ele_isBarrel, &b_ele_isBarrel);
   fChain->SetBranchAddress("ele_isEndcap", ele_isEndcap, &b_ele_isEndcap);
   fChain->SetBranchAddress("ele_eta", ele_eta, &b_ele_eta);
   fChain->SetBranchAddress("ele_phi", ele_phi, &b_ele_phi);
   fChain->SetBranchAddress("ele_dxy", ele_dxy, &b_ele_dxy);
   fChain->SetBranchAddress("ele_pt", ele_pt, &b_ele_pt);
   fChain->SetBranchAddress("ele_energy", ele_energy, &b_ele_energy);
   fChain->SetBranchAddress("ele_ecalenergy", ele_ecalenergy, &b_ele_ecalenergy);
   fChain->SetBranchAddress("ele_ecalenergyerror", ele_ecalenergyerror, &b_ele_ecalenergyerror);
   fChain->SetBranchAddress("ele_et", ele_et, &b_ele_et);
   fChain->SetBranchAddress("ele_p", ele_p, &b_ele_p);
   fChain->SetBranchAddress("ele_electronmomentumerror", ele_electronmomentumerror, &b_ele_electronmomentumerror);
   fChain->SetBranchAddress("ele_px", ele_px, &b_ele_px);
   fChain->SetBranchAddress("ele_py", ele_py, &b_ele_py);
   fChain->SetBranchAddress("ele_pz", ele_pz, &b_ele_pz);
   fChain->SetBranchAddress("ele_deltaetaeleclustertrackatcalo", ele_deltaetaeleclustertrackatcalo, &b_ele_deltaetaeleclustertrackatcalo);
   fChain->SetBranchAddress("ele_deltaetaseedclustertrackatcalo", ele_deltaetaseedclustertrackatcalo, &b_ele_deltaetaseedclustertrackatcalo);
   fChain->SetBranchAddress("ele_deltaetasuperclustertrackatvtx", ele_deltaetasuperclustertrackatvtx, &b_ele_deltaetasuperclustertrackatvtx);
   fChain->SetBranchAddress("ele_deltaphieleclustertrackatcalo", ele_deltaphieleclustertrackatcalo, &b_ele_deltaphieleclustertrackatcalo);
   fChain->SetBranchAddress("ele_deltaphiseedclustertrackatcalo", ele_deltaphiseedclustertrackatcalo, &b_ele_deltaphiseedclustertrackatcalo);
   fChain->SetBranchAddress("ele_deltaphisuperclustertrackatvtx", ele_deltaphisuperclustertrackatvtx, &b_ele_deltaphisuperclustertrackatvtx);
   fChain->SetBranchAddress("ele_trackpositionatvtxx", ele_trackpositionatvtxx, &b_ele_trackpositionatvtxx);
   fChain->SetBranchAddress("ele_trackpositionatvtxy", ele_trackpositionatvtxy, &b_ele_trackpositionatvtxy);
   fChain->SetBranchAddress("ele_trackpositionatvtxz", ele_trackpositionatvtxz, &b_ele_trackpositionatvtxz);
   fChain->SetBranchAddress("ele_trackmomentumatvtxx", ele_trackmomentumatvtxx, &b_ele_trackmomentumatvtxx);
   fChain->SetBranchAddress("ele_trackmomentumatvtxy", ele_trackmomentumatvtxy, &b_ele_trackmomentumatvtxy);
   fChain->SetBranchAddress("ele_trackmomentumatvtxz", ele_trackmomentumatvtxz, &b_ele_trackmomentumatvtxz);
   fChain->SetBranchAddress("ele_trackpositionatcalox", ele_trackpositionatcalox, &b_ele_trackpositionatcalox);
   fChain->SetBranchAddress("ele_trackpositionatcaloy", ele_trackpositionatcaloy, &b_ele_trackpositionatcaloy);
   fChain->SetBranchAddress("ele_trackpositionatcaloz", ele_trackpositionatcaloz, &b_ele_trackpositionatcaloz);
   fChain->SetBranchAddress("ele_trackmomentumatcalox", ele_trackmomentumatcalox, &b_ele_trackmomentumatcalox);
   fChain->SetBranchAddress("ele_trackmomentumatcaloy", ele_trackmomentumatcaloy, &b_ele_trackmomentumatcaloy);
   fChain->SetBranchAddress("ele_trackmomentumatcaloz", ele_trackmomentumatcaloz, &b_ele_trackmomentumatcaloz);
   fChain->SetBranchAddress("ele_eeleclusteroverpout", ele_eeleclusteroverpout, &b_ele_eeleclusteroverpout);
   fChain->SetBranchAddress("ele_eseedclusteroverp", ele_eseedclusteroverp, &b_ele_eseedclusteroverp);
   fChain->SetBranchAddress("ele_eseedclusteroverpout", ele_eseedclusteroverpout, &b_ele_eseedclusteroverpout);
   fChain->SetBranchAddress("ele_esuperclusteroverp", ele_esuperclusteroverp, &b_ele_esuperclusteroverp);
   fChain->SetBranchAddress("ele_dr03ecalrechitsumet", ele_dr03ecalrechitsumet, &b_ele_dr03ecalrechitsumet);
   fChain->SetBranchAddress("ele_dr03hcaldepth1towersumet", ele_dr03hcaldepth1towersumet, &b_ele_dr03hcaldepth1towersumet);
   fChain->SetBranchAddress("ele_dr03hcaldepth2towersumet", ele_dr03hcaldepth2towersumet, &b_ele_dr03hcaldepth2towersumet);
   fChain->SetBranchAddress("ele_dr03hcaltowersumet", ele_dr03hcaltowersumet, &b_ele_dr03hcaltowersumet);
   fChain->SetBranchAddress("ele_dr03tksumpt", ele_dr03tksumpt, &b_ele_dr03tksumpt);
   fChain->SetBranchAddress("ele_dr04ecalrechitsumet", ele_dr04ecalrechitsumet, &b_ele_dr04ecalrechitsumet);
   fChain->SetBranchAddress("ele_dr04hcaldepth1towersumet", ele_dr04hcaldepth1towersumet, &b_ele_dr04hcaldepth1towersumet);
   fChain->SetBranchAddress("ele_dr04hcaldepth2towersumet", ele_dr04hcaldepth2towersumet, &b_ele_dr04hcaldepth2towersumet);
   fChain->SetBranchAddress("ele_dr04hcaltowersumet", ele_dr04hcaltowersumet, &b_ele_dr04hcaltowersumet);
   fChain->SetBranchAddress("ele_dr04tksumpt", ele_dr04tksumpt, &b_ele_dr04tksumpt);
   fChain->SetBranchAddress("ele_e1x5", ele_e1x5, &b_ele_e1x5);
   fChain->SetBranchAddress("ele_e2x5max", ele_e2x5max, &b_ele_e2x5max);
   fChain->SetBranchAddress("ele_e5x5", ele_e5x5, &b_ele_e5x5);
   fChain->SetBranchAddress("ele_r1x5", ele_r1x5, &b_ele_r1x5);
   fChain->SetBranchAddress("ele_r2x5max", ele_r2x5max, &b_ele_r2x5max);
   fChain->SetBranchAddress("ele_scpreshowerenergy", ele_scpreshowerenergy, &b_ele_scpreshowerenergy);
   fChain->SetBranchAddress("ele_scetawidth", ele_scetawidth, &b_ele_scetawidth);
   fChain->SetBranchAddress("ele_scphiwidth", ele_scphiwidth, &b_ele_scphiwidth);
   fChain->SetBranchAddress("ele_scr9", ele_scr9, &b_ele_scr9);
   fChain->SetBranchAddress("ele_sceseedoveresupercluster", ele_sceseedoveresupercluster, &b_ele_sceseedoveresupercluster);
   fChain->SetBranchAddress("ele_rmax3x3", ele_rmax3x3, &b_ele_rmax3x3);
   fChain->SetBranchAddress("ele_hcaldepth1overecal", ele_hcaldepth1overecal, &b_ele_hcaldepth1overecal);
   fChain->SetBranchAddress("ele_hcaldepth2overecal", ele_hcaldepth2overecal, &b_ele_hcaldepth2overecal);
   fChain->SetBranchAddress("ele_hcaloverecal", ele_hcaloverecal, &b_ele_hcaloverecal);
   fChain->SetBranchAddress("ele_sigmaetaeta", ele_sigmaetaeta, &b_ele_sigmaetaeta);
   fChain->SetBranchAddress("ele_sigmaietaieta", ele_sigmaietaieta, &b_ele_sigmaietaieta);
   fChain->SetBranchAddress("ele_basicclusterssize", ele_basicclusterssize, &b_ele_basicclusterssize);
   fChain->SetBranchAddress("ele_numberofbrems", ele_numberofbrems, &b_ele_numberofbrems);
   fChain->SetBranchAddress("ele_fbrem", ele_fbrem, &b_ele_fbrem);
   fChain->SetBranchAddress("ele_scpixcharge", ele_scpixcharge, &b_ele_scpixcharge);
   fChain->SetBranchAddress("ele_gsfcharge", ele_gsfcharge, &b_ele_gsfcharge);
   fChain->SetBranchAddress("ele_ctfcharge", ele_ctfcharge, &b_ele_ctfcharge);
   fChain->SetBranchAddress("ele_isgsfscpixchargeconsistent", ele_isgsfscpixchargeconsistent, &b_ele_isgsfscpixchargeconsistent);
   fChain->SetBranchAddress("ele_isgsfctfchargeconsistent", ele_isgsfctfchargeconsistent, &b_ele_isgsfctfchargeconsistent);
   fChain->SetBranchAddress("ele_isgsfctfscpixchargeconsistent", ele_isgsfctfscpixchargeconsistent, &b_ele_isgsfctfscpixchargeconsistent);
   fChain->SetBranchAddress("ele_charge", ele_charge, &b_ele_charge);
   fChain->SetBranchAddress("ele_vertexChi2", ele_vertexChi2, &b_ele_vertexChi2);
   fChain->SetBranchAddress("ele_vertexNdof", ele_vertexNdof, &b_ele_vertexNdof);
   fChain->SetBranchAddress("ele_vertexNormalizedChi2", ele_vertexNormalizedChi2, &b_ele_vertexNormalizedChi2);
   fChain->SetBranchAddress("ele_vx", ele_vx, &b_ele_vx);
   fChain->SetBranchAddress("ele_vy", ele_vy, &b_ele_vy);
   fChain->SetBranchAddress("ele_vz", ele_vz, &b_ele_vz);
   fChain->SetBranchAddress("ele_nexpectedinnerhits", ele_nexpectedinnerhits, &b_ele_nexpectedinnerhits);
   fChain->SetBranchAddress("ele_dist", ele_dist, &b_ele_dist);
   fChain->SetBranchAddress("ele_dcottheta", ele_dcottheta, &b_ele_dcottheta);
   fChain->SetBranchAddress("sc_nSuperClusters", &sc_nSuperClusters, &b_sc_nSuperClusters);
   fChain->SetBranchAddress("hlt_nHltObj_Elec10", &hlt_nHltObj_Elec10, &b_hlt_nHltObj_Elec10);
   fChain->SetBranchAddress("hlt_nHltObj_Elec15", &hlt_nHltObj_Elec15, &b_hlt_nHltObj_Elec15);
   fChain->SetBranchAddress("hlt_nHltObj_Phot10", &hlt_nHltObj_Phot10, &b_hlt_nHltObj_Phot10);
   fChain->SetBranchAddress("hlt_nHltObj_Phot15", &hlt_nHltObj_Phot15, &b_hlt_nHltObj_Phot15);
   fChain->SetBranchAddress("hlt_Elec10_et", hlt_Elec10_et, &b_hlt_Elec10_et);
   fChain->SetBranchAddress("hlt_Elec10_eta", hlt_Elec10_eta, &b_hlt_Elec10_eta);
   fChain->SetBranchAddress("hlt_Elec10_phi", hlt_Elec10_phi, &b_hlt_Elec10_phi);
   fChain->SetBranchAddress("hlt_Elec15_et", hlt_Elec15_et, &b_hlt_Elec15_et);
   fChain->SetBranchAddress("hlt_Elec15_eta", hlt_Elec15_eta, &b_hlt_Elec15_eta);
   fChain->SetBranchAddress("hlt_Phot10_et", hlt_Phot10_et, &b_hlt_Phot10_et);
   fChain->SetBranchAddress("hlt_Phot10_eta", hlt_Phot10_eta, &b_hlt_Phot10_eta);
   fChain->SetBranchAddress("hlt_Phot10_phi", hlt_Phot10_phi, &b_hlt_Phot10_phi);
   fChain->SetBranchAddress("hlt_Phot15_et", hlt_Phot15_et, &b_hlt_Phot15_et);
   fChain->SetBranchAddress("hlt_Phot15_eta", hlt_Phot15_eta, &b_hlt_Phot15_eta);
   fChain->SetBranchAddress("hlt_Phot15_phi", hlt_Phot15_phi, &b_hlt_Phot15_phi);
   fChain->SetBranchAddress("l1_nL1Obj", &l1_nL1Obj, &b_l1_nL1Obj);
   fChain->SetBranchAddress("l1_et", l1_et, &b_l1_et);
   fChain->SetBranchAddress("l1_eta", l1_eta, &b_l1_eta);
   fChain->SetBranchAddress("l1_phi", l1_phi, &b_l1_phi);
   fChain->SetBranchAddress("sc_nSuperClustersBarrel", &sc_nSuperClustersBarrel, &b_sc_nSuperClustersBarrel);
   fChain->SetBranchAddress("sc_nSuperClustersEndcap", &sc_nSuperClustersEndcap, &b_sc_nSuperClustersEndcap);
   fChain->SetBranchAddress("sc_isBarrel", sc_isBarrel, &b_sc_isBarrel);
   fChain->SetBranchAddress("sc_isEndcap", sc_isEndcap, &b_sc_isEndcap);
   fChain->SetBranchAddress("sc_energy", sc_energy, &b_sc_energy);
   fChain->SetBranchAddress("sc_eta", sc_eta, &b_sc_eta);
   fChain->SetBranchAddress("sc_phi", sc_phi, &b_sc_phi);
   fChain->SetBranchAddress("sc_et", sc_et, &b_sc_et);
   fChain->SetBranchAddress("sc_rawEnergy", sc_rawEnergy, &b_sc_rawEnergy);
   fChain->SetBranchAddress("sc_preshowerEnergy", sc_preshowerEnergy, &b_sc_preshowerEnergy);
   fChain->SetBranchAddress("sc_etaWidth", sc_etaWidth, &b_sc_etaWidth);
   fChain->SetBranchAddress("sc_phiWidth", sc_phiWidth, &b_sc_phiWidth);
   fChain->SetBranchAddress("sc_nBasicClusters", sc_nBasicClusters, &b_sc_nBasicClusters);
   fChain->SetBranchAddress("sc_r9", sc_r9, &b_sc_r9);
   fChain->SetBranchAddress("sc_eSeedOverESuperCluster", sc_eSeedOverESuperCluster, &b_sc_eSeedOverESuperCluster);
   Notify();
}

Bool_t EwkDqmTree::Notify()
{
   // The Notify() function is called when a new file is opened. This
   // can be either for a new TTree in a TChain or when when a new TTree
   // is started when using PROOF. It is normally not necessary to make changes
   // to the generated code, but the routine can be extended by the
   // user if needed. The return value is currently not used.

   return kTRUE;
}

void EwkDqmTree::Show(Long64_t entry)
{
// Print contents of entry.
// If entry is not specified, print current entry
   if (!fChain) return;
   fChain->Show(entry);
}
Int_t EwkDqmTree::Cut(Long64_t entry)
{
// This function may be called from Loop.
// returns  1 if entry is accepted.
// returns -1 otherwise.
   return 1;
}
#endif // #ifdef EwkDqmTree_cxx
